//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfClient.WebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServices.ICurrencyService")]
    public interface ICurrencyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/ListAll", ReplyAction="http://tempuri.org/ICurrencyService/ListAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Core.Entities.CurrenciesPairRate>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Core.Entities.CurrenciesPairRate))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Core.Entities.BaseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Core.Entities.CurrenciesPair))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Core.Entities.Currency))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<System.DateTime, System.Collections.Generic.List<Core.Entities.CurrenciesPairRate>>))]
        object ListAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/ListAll", ReplyAction="http://tempuri.org/ICurrencyService/ListAllResponse")]
        System.Threading.Tasks.Task<object> ListAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/ListByPeriod", ReplyAction="http://tempuri.org/ICurrencyService/ListByPeriodResponse")]
        System.Collections.Generic.Dictionary<System.DateTime, System.Collections.Generic.List<Core.Entities.CurrenciesPairRate>> ListByPeriod(int year, int month);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurrencyService/ListByPeriod", ReplyAction="http://tempuri.org/ICurrencyService/ListByPeriodResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<System.DateTime, System.Collections.Generic.List<Core.Entities.CurrenciesPairRate>>> ListByPeriodAsync(int year, int month);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyServiceChannel : WpfClient.WebServices.ICurrencyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyServiceClient : System.ServiceModel.ClientBase<WpfClient.WebServices.ICurrencyService>, WpfClient.WebServices.ICurrencyService {
        
        public CurrencyServiceClient() {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public object ListAll() {
            return base.Channel.ListAll();
        }
        
        public System.Threading.Tasks.Task<object> ListAllAsync() {
            return base.Channel.ListAllAsync();
        }
        
        public System.Collections.Generic.Dictionary<System.DateTime, System.Collections.Generic.List<Core.Entities.CurrenciesPairRate>> ListByPeriod(int year, int month) {
            return base.Channel.ListByPeriod(year, month);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<System.DateTime, System.Collections.Generic.List<Core.Entities.CurrenciesPairRate>>> ListByPeriodAsync(int year, int month) {
            return base.Channel.ListByPeriodAsync(year, month);
        }
    }
}
